<a href="https://colab.research.google.com/github/Roman53736/python-AI/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Practice_ipynb11%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 1
b = 3
print(a+b)

4


In [ ]:
import numpy


In [ ]:
with open('file.txt', 'w') as f:
  f.write('hello')

In [ ]:
!pip install numpy

In [1]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

NameError: name 'np' is not defined

In [4]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
b = a[:-1, 1:3]
print(b)

[[2 3]
 [6 7]]


In [6]:
a[:-1, 1:3] = [[-2, -3], [4, 5]]
print(a)

[[ 1 -2 -3  4]
 [ 5  4  5  8]
 [ 9 10 11 12]]


In [7]:
print(a[0:3, 0:-3])

[[1]
 [5]
 [9]]


In [9]:
print(a[[0,1,2], [0,1,0]])

print()

[1 4 9]



In [14]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 9]


In [17]:
j = np.array([[1, 2], [4, 5], [0, 6]])
bool_idx = (a > 2)
print(a)
print(a[bool_idx])

[[ 1 -2 -3  4]
 [ 5  4  5  8]
 [ 9 10 11 12]]
[ 4  5  4  5  8  9 10 11 12]


In [16]:
print(a[bool_idx])

[ 4  5  4  5  8  9 10 11 12]


In [18]:
print(a[a > 2])

[ 4  5  4  5  8  9 10 11 12]


In [25]:
print(a[(a > 2) & (a < 5)])
print(a[(a > 2)])
print(a[(a < 5)])
print(a[~(a > 5)])

[4 4]
[ 4  5  4  5  8  9 10 11 12]
[ 1 -2 -3  4  4]
[ 1 -2 -3  4  5  4  5]


In [30]:
a = np.array([1, 2, 3, 4, 7, 8, 9, 0, -1])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a)[::-1])
print(a[np.argsort(a)])


6
8
[6 5 4 3 2 1 0 7 8]
[-1  0  1  2  3  4  7  8  9]


In [37]:
t = np.array([122], dtype=np.int8)
t += 1


In [42]:

a = np.random.random(10000000)
print(a)


[0.66391125 0.65614648 0.53549825 ... 0.03189601 0.25227043 0.31285481]


In [43]:
%%time
x = np.sum(a)

CPU times: user 13 ms, sys: 0 ns, total: 13 ms
Wall time: 11.8 ms


In [47]:
%%time
x = 0
for element in a:
  x = x + element

CPU times: user 1.97 s, sys: 0 ns, total: 1.97 s
Wall time: 1.97 s
